# Generated by Django 5.1.6 on 2025-02-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contactmessage_subject_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickuplocation', models.CharField(choices=[('kollam', 'Kollam'), ('koyilandy', 'Koyilandy'), ('payyoli', 'Payyoli'), ('nandi', 'Nandi'), ('vatakara', 'Vatakara'), ('kozhikode', 'Kozhikode'), ('other', 'Other')], max_length=20)),
                ('droplocation', models.CharField(choices=[('kollam', 'Kollam'), ('koyilandy', 'Koyilandy'), ('payyoli', 'Payyoli'), ('nandi', 'Nandi'), ('vatakara', 'Vatakara'), ('kozhikode', 'Kozhikode'), ('other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('pickuptime', models.TimeField()),
                ('cartype', models.CharField(choices=[('maruti', 'Maruti'), ('chevrolet', 'Chevrolet'), ('bmw', 'BMW'), ('mercedes', 'Mercedes'), ('toyota', 'Toyota'), ('honda', 'Honda'), ('hyundai', 'Hyundai'), ('volkswagen', 'Volkswagen'), ('skoda', 'Skoda')], max_length=20)),
            ],
        ),
    ]
